version: '2'
# 单broker，用于测试
services:
  zoo1:
    image: wurstmeister/zookeeper
    #    restart: unless-stopped
    hostname: zoo1
    ports:
    - "2182:2181"
    container_name: kafka-zookeeper
  kafka1:
    image: wurstmeister/kafka:2.11-0.11.0.2
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
    - zoo1
    container_name: kafka
  kafkaM1:
    image: hlebalbau/kafka-manager
    ports:
    - "9998:9000"
    environment:
      ZK_HOSTS: "zoo1:2181"
    depends_on:
    - zoo1
    container_name: kafka-manager