#!/usr/bin/env bash

# kafka-manager
https://github.com/yahoo/kafka-manager

# shell
# list topic
kafka-topics.sh --zookeeper zoo1:2181 --list
kafka-topics.sh --describe --zookeeper zoo1:2181 --topic test

./kafka-topics.sh --create --zookeeper zoo1:2181 --replication-factor 2 --partitions 3 --topic test
kafka-console-producer.sh --broker-list kafka1:9092 --topic test
kafka-console-consumer.sh --bootstrap-server kafka1:9092 --topic test --from-beginning